"""Auto migration

Revision ID: 304cf75f7573
Revises: e9fa2c8e08d8
Create Date: 2025-10-08 13:44:58.414267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304cf75f7573'
down_revision: Union[str, None] = 'e9fa2c8e08d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personas')
    op.add_column('users', sa.Column('hashed_password', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.create_table('personas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('system_prompt', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.Column('avatar_color', sa.VARCHAR(length=20), nullable=True),
    sa.Column('personality_traits', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###